title: Compound III Documentation Site
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

compress_html:
  comments: ["<!-- ", " -->"]

## Page Name Anchor Text: Anchor HREF
v3_nav_data:
  # Compound III: / ## This is now a toggle switch between v2 and v3 docs
  Interest Rates: /interest-rates/
  Collateral & Borrowing: /collateral-and-borrowing/
  Liquidation: /liquidation/
  Account Management: /account-management/
  Protocol Rewards: /protocol-rewards/
  Governance: /governance/
  Helper Functions: /helper-functions/

v2_nav_data:
  # Compound v2: /v2/
  cTokens: /v2/ctokens/
  Comptroller: /v2/comptroller/
  Governance: /v2/governance/
  Open Price Feed: /v2/prices/
  API: /v2/api/
  Security: /v2/security/

compound_js_nav_data: 
  # Compound.js: /compound-js/
  Comet: /compound-js/comet/
  Governance: /compound-js/governance/
  cTokens (v2): /compound-js/ctokens/
  Comptroller (v2): /compound-js/comptroller/
  Price Feed (v2): /compound-js/price-feed/
  API (v2): /compound-js/api/
  Helpers: /compound-js/helpers/